/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dialog.OptionDialog;
import forms.student.about.AboutForm;
import forms.student.info.EditStudentInfoForm;
import forms.student.info.StudentInfoForm;
import forms.student.login.NewLoginForm;
import helper.FrameHelper;
import javax.swing.*;
import user.AuthUser;

/**
 * @author misterfocusth
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        aboutProgrameMenu = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        studentInfoMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        editStudentInfoMenu = new javax.swing.JMenuItem();
        docRequestMenu = new javax.swing.JMenu();
        contactStaffMenu = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainDesktopPane.setBackground(new java.awt.Color(19, 169, 240));
        mainDesktopPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        jMenuBar2.setPreferredSize(new java.awt.Dimension(690, 35));

        aboutProgrameMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icons/icons8-info-28.png"))); // NOI18N
        aboutProgrameMenu.setText("เกี่ยวกับโปรเเกรม");
        aboutProgrameMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        aboutProgrameMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutProgrameMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(aboutProgrameMenu);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icons/icons8-male-user-28.png"))); // NOI18N
        jMenu5.setText("ข้อมูลนักศึกษา");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        studentInfoMenu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        studentInfoMenu.setText("ข้อมูลนึกศึกษา");
        studentInfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoMenuActionPerformed(evt);
            }
        });
        jMenu5.add(studentInfoMenu);
        jMenu5.add(jSeparator1);

        editStudentInfoMenu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        editStudentInfoMenu.setText("เเก้ไขข้อมูลส่วนตัว");
        editStudentInfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentInfoMenuActionPerformed(evt);
            }
        });
        jMenu5.add(editStudentInfoMenu);

        jMenuBar2.add(jMenu5);

        docRequestMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icons/icons8-documents-28.png"))); // NOI18N
        docRequestMenu.setText("เอกสารเเละคำร้องทางการศึกษา");
        docRequestMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenuBar2.add(docRequestMenu);

        contactStaffMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icons/icons8-faq-28.png"))); // NOI18N
        contactStaffMenu.setText("ถามตอบห้องฟ้า");
        contactStaffMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenuBar2.add(contactStaffMenu);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icons/icons8-today-28.png"))); // NOI18N
        jMenu9.setText("เช็คชื่อเข้าชั้นเรียน");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenuBar2.add(jMenu9);

        logoutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icons/icons8-logout-28.png"))); // NOI18N
        logoutMenu.setText("ออกจากระบบ");
        logoutMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(logoutMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        // ออกจากระบบ
        int selectedOpt = new OptionDialog("ออกจากระบบ", "ยืนยันที่จะออกจากระบบ หรือไม่ ?").show();
        if (selectedOpt == 0) {
            AuthUser.setAuthUser(null);
            NewLoginForm newLoginForm = new NewLoginForm();
            newLoginForm.setLocationRelativeTo(null);
            newLoginForm.setVisible(true);
            this.setVisible(false);
            this.dispose();

            MainForm.mainDesktopPane.removeAll();
            MainForm.mainDesktopPane.updateUI();
        }
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void studentInfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoMenuActionPerformed
        // TODO add your handling code here:
        StudentInfoForm homeForm = new StudentInfoForm();
        FrameHelper.setLocationToCenter(homeForm);
        MainForm.mainDesktopPane.add(homeForm);
        homeForm.setVisible(true);
    }//GEN-LAST:event_studentInfoMenuActionPerformed

    private void aboutProgrameMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutProgrameMenuMouseClicked
        // TODO add your handling code here:
        AboutForm aboutForm = new AboutForm();
        aboutForm.setLocationRelativeTo(null);
        aboutForm.setVisible(true);
    }//GEN-LAST:event_aboutProgrameMenuMouseClicked

    private void editStudentInfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentInfoMenuActionPerformed
        // TODO add your handling code here:
        EditStudentInfoForm editStudentInfoForm = new EditStudentInfoForm();
        FrameHelper.setLocationToCenter(editStudentInfoForm);
        MainForm.mainDesktopPane.add(editStudentInfoForm);
        editStudentInfoForm.setVisible(true);
    }//GEN-LAST:event_editStudentInfoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });

    }

    public JDesktopPane getMainDesktopPane() {
        return mainDesktopPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutProgrameMenu;
    private javax.swing.JMenu contactStaffMenu;
    private javax.swing.JMenu docRequestMenu;
    private javax.swing.JMenuItem editStudentInfoMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu logoutMenu;
    public static final javax.swing.JDesktopPane mainDesktopPane = new javax.swing.JDesktopPane();
    private javax.swing.JMenuItem studentInfoMenu;
    // End of variables declaration//GEN-END:variables
}
