/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package forms.student.subject;

/**
 *
 * @author WINDOWS 10
 */
public class CheckSuccessForms extends javax.swing.JInternalFrame {

    /**
     * Creates new form CheckSuccessForms
     */
    public CheckSuccessForms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalLabel = new javax.swing.JLabel();
        backhomebtn = new javax.swing.JButton();

        finalLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        finalLabel.setText("เช็คชื่อสำเร็จ");

        backhomebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backhomebtn.setText("กลับสู่หน้าหลัก");
        backhomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhomebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(finalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(backhomebtn)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(finalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backhomebtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backhomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhomebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backhomebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backhomebtn;
    private javax.swing.JLabel finalLabel;
    // End of variables declaration//GEN-END:variables
}
